# Generated by Django 5.2.1 on 2025-05-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('خانوادگی', 'خانوادگی'), ('عمده', 'عمده'), ('تخفیفی', 'تخفیفی')], null=True),
        ),
    ]
